name: Build Room Server Firmwares

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build from"
        required: true
        default: "dev-slunsecore"
        type: choice
        options:
          - dev-slunsecore
          - slunsecore
  push:
    branches:
      - slunsecore
    tags:
      - "slunsecore-room-server-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-environment

      - name: Build Firmwares
        env:
          FIRMWARE_VERSION: ${{ env.GIT_TAG_VERSION || env.GIT_COMMIT_VERSION }}
          BUILD_BRANCH: ${{ github.event.inputs.branch || github.ref_name }}
        run: /usr/bin/env bash build.sh build-room-server-firmwares

      - name: Upload Workflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: room-server-firmwares
          path: out

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Slunsecore Room Server Firmware ${{ env.GIT_TAG_VERSION }}
          body: ""
          draft: true
          files: out/*
