name: Build Repeater Firmwares

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build from"
        required: true
        default: "dev-slunsecore"
        type: choice
        options:
          - dev-slunsecore
          - slunsecore
  push:
    tags:
      - "sc-repeater-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-environment

      - name: Build Firmwares
        env:
          FIRMWARE_VERSION: ${{ env.GIT_TAG_VERSION || env.GIT_COMMIT_VERSION }}
          BUILD_BRANCH: ${{ github.event.inputs.branch || github.ref_name }}
        run: /usr/bin/env bash build.sh build-repeater-firmwares

      - name: Upload Workflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: repeater-firmwares
          path: out

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: SlunseCore Repeater Firmware ${{ env.GIT_TAG_VERSION }}
          body: "See latest commits"
          draft: true
          files: out/*
